# Generated by Django 5.1.5 on 2025-02-06 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], db_index=True, max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in card primary currency', max_digits=15)),
                ('card', models.CharField(blank=True, help_text='Card identifier if multiple cards exist', max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('entertainment', 'Entertainment'), ('digital_goods', 'Digital Goods'), ('food_drink', 'Food & Drink'), ('other', 'Other')], max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, help_text='e.g., UAH, USD', max_length=10, null=True)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('original_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('balance_after_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'), models.Index(fields=['type', 'date'], name='transaction_type_1ffefc_idx')],
            },
        ),
    ]
